export const RANDOM_QUOTE = [
  'My top-notch skill',
  'That one was quite intense',
  'Pretty impressive, huh?',
  'Keep exploring',
  "This one's my favorite",
  'I truly excelled in this one',
  'It was a challenging period...',
  'Great choice, thanks!',
  'It was totally worth it',
  'Could there be an easter egg?',
  'Consider hiring me',
  'Good pick',
  'Spent 1000 hours perfecting the basics',
  'Mastered it to perfection',
  "Can't get enough of this one",
  "A skill I'm really proud of",
  "Who knew I'd get this good?",
  'Learned from the best',
  'A true game-changer',
  'No mountain too high',
  'The journey was worth it',
  'Pushed my limits with this one',
  "I've come a long way with this skill",
];
